apiVersion: v1
kind: Service
metadata:
  name: k8springdocker-k8s-service
spec:
    selector:
        app: K8SpringDocker
    ports:
      - protocol: TCP
        port: 8080  #ClusterIP port
        targetPort: 8080  #Container port exposed by the pod
    type: NodePort  #Service type can be ClusterIP, NodePort, LoadBalancer, ExternalName